show user;
select * from all_sys_privs;
create table testTable(match_id NUMBER(20));
CREATE TABLE matches(
    match_id NUMBER(11),
    players_hero_id NUMBER(3),
    players_player_slot NUMBER(2),
    --players_ability_upgrades_arr NUMBER(),
    players_account_id NUMBER(20),
    players_assists NUMBER(3),
    players_deaths NUMBER(3),
    players_kills NUMBER(3),
    players_towers_killed NUMBER(3),
    players_courier_kills NUMBER(3),
    players_observer_kills NUMBER(3),
    players_sentry_kills NUMBER(3),
    players_lane_role NUMBER(3),
    players_gold NUMBER(5),
    players_gold_per_min NUMBER(5),
    players_xp_per_min NUMBER(8),
    players_total_gold NUMBER(5),
    players_total_xp NUMBER(8),
    players_actions_per_mindenies NUMBER(4),
    players_ancient_kills NUMBER(4),
    players_last_hits NUMBER(4),
    players_camps_stacked NUMBER(4),
    players_gold_spent NUMBER(5),
    players_gold_t NUMBER(5),
    players_hero_damage NUMBER(7),
    players_hero_healing NUMBER(7),
    players_tower_damage NUMBER(7),
    --players_item_0 NUMBER(),
    --players_item_1 NUMBER(),
    --players_item_2 NUMBER(),
    --players_item_3 NUMBER(),
    --players_item_4 NUMBER(),
    --players_item_5 NUMBER(),
    --players_item_neutral NUMBER(),
    players_level NUMBER(2),
    players_obs_placed NUMBER(3),
    players_lh_t NUMBER(5),
    players_xp_t NUMBER(5),
    players_stuns NUMBER(5),
    players_personaname VARCHAR(50),
    players_name VARCHAR(50),
    players_is_roaming BOOLEAN,
    barracks_status_dire NUMBER(2),
    barracks_status_radiant NUMBER(2),
    dire_score NUMBER(3),
    radiant_score NUMBER(3),
    dire_team_id NUMBER(10),
    radiant_team_id NUMBER(10),
    --draft_timings
    duration_value NUMBER(10),
    --engine NUMBER(4),
    first_blood_time NUMBER(10),
    game_mode NUMBER(3),
    human_players NUMBER(2),
    leagueid NUMBER(5),
    lobby_type NUMBER(3),
    match_seq_num NUMBER(11),
    negative_votes NUMBER(3),
    positive_votes NUMBER(3),
    radiant_gold_adv NUMBER(6),
    radiant_xp_adv NUMBER(7),
    radiant_win BOOLEAN,
    skill NUMBER(3),
    start_time NUMBER(11),
    tower_status_dire NUMBER(4),
    tower_status_radiant NUMBER(4),
    version_value NUMBER(4),
    replay_salt NUMBER(11),
    series_id NUMBER(11),
    series_type NUMBER(3),
    --league_league
    --radiant_team_team
    --dire_team_team
    patch_value NUMBER(3),
    replay_url VARCHAR(200)
    --pick_bans NUMBER(),
    --teamFights NUMBER()
);